using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Text;
using Base.UtilityPackage.Logging;
using UnityEditor;

namespace Base.ToolsPackage.Editor.OrderManagement
{
    /// <summary>Writes the generated constants file from an <see cref="OrderRegistry"/>.</summary>
    internal static class OrderCodeGenerator
    {
        private const string FileExtension = ".cs";
        private const string Indent = "    ";

        /// <summary>Generates the constants file and refreshes the AssetDatabase.</summary>
        internal static void Generate(OrderRegistry registry)
        {
            if (registry == null)
                return;

            if (registry.Constants.Count == 0)
            {
                CustomLogger.LogWarning("Order Manager: no constants defined, generation skipped.", null);
                return;
            }

            string code = BuildCode(registry.GeneratedNamespace, registry.RootClassName, registry.Constants,
                out int count);

            string fileName = registry.RootClassName + FileExtension;
            string fullPath = Path.GetFullPath(Path.Combine(registry.OutputDirectory, fileName));
            string directory = Path.GetDirectoryName(fullPath);

            if (!string.IsNullOrEmpty(directory) && !Directory.Exists(directory))
                Directory.CreateDirectory(directory);

            File.WriteAllText(fullPath, code, Encoding.UTF8);
            AssetDatabase.Refresh();

            CustomLogger.Log($"Order Manager: generated {count} constant(s) to {fullPath}.", null);
        }

        /// <summary>
        /// Builds the file's text. Separate from <see cref="Generate"/> and free of the registry, which
        /// is a <c>ScriptableSingleton</c> backed by a file in <c>ProjectSettings</c>: what is emitted
        /// has to compile, and nothing could check that while producing it meant writing to disk.
        /// </summary>
        /// <param name="generatedNamespace">Namespace the class is declared in.</param>
        /// <param name="rootClassName">Name of the generated static class.</param>
        /// <param name="constants">The constants to emit, in any order.</param>
        /// <param name="count">Receives how many constants were actually emitted.</param>
        /// <returns>The full text of the generated file.</returns>
        internal static string BuildCode(string generatedNamespace, string rootClassName,
            IReadOnlyList<OrderConstant> constants, out int count)
        {
            StringBuilder builder = new();
            builder.AppendLine("// <auto-generated>");
            builder.AppendLine("// Generated by the Order Manager. Do not edit by hand.");
            builder.AppendLine("// </auto-generated>");
            builder.AppendLine();
            builder.Append("namespace ").AppendLine(generatedNamespace);
            builder.AppendLine("{");
            builder.Append(Indent).Append("public static class ").AppendLine(rootClassName);
            builder.Append(Indent).AppendLine("{");

            count = AppendConstants(builder, constants);

            builder.Append(Indent).AppendLine("}");
            builder.AppendLine("}");
            return builder.ToString();
        }

        private static int AppendConstants(StringBuilder builder, IReadOnlyList<OrderConstant> constants)
        {
            List<OrderConstant> sorted = new(constants);
            sorted.Sort(CompareConstants);

            HashSet<string> usedNames = new();
            const string lineIndent = Indent + Indent;
            int count = 0;

            foreach (OrderConstant constant in sorted)
            {
                string constantName = ToValidIdentifier(constant.Name);

                if (string.IsNullOrEmpty(constantName))
                    continue;

                if (!usedNames.Add(constantName))
                {
                    CustomLogger.LogWarning($"Order Manager: duplicate constant name '{constantName}' skipped.", null);
                    continue;
                }

                if (count > 0)
                    builder.AppendLine();

                AppendXmlSummary(builder, lineIndent, constant.Comment);
                builder.Append(lineIndent)
                    .Append("public const int ")
                    .Append(constantName)
                    .Append(" = ")
                    .Append(constant.Value.ToString(CultureInfo.InvariantCulture))
                    .AppendLine(";");

                count++;
            }

            return count;
        }

        private static void AppendXmlSummary(StringBuilder builder, string indent, string comment)
        {
            if (string.IsNullOrWhiteSpace(comment))
                return;

            string[] lines = Escape(comment).Split('\n');

            if (lines.Length == 1)
            {
                builder.Append(indent).Append("/// <summary>").Append(lines[0].Trim()).AppendLine("</summary>");
                return;
            }

            builder.Append(indent).AppendLine("/// <summary>");

            foreach (string line in lines)
                builder.Append(indent).Append("/// ").AppendLine(line.TrimEnd());

            builder.Append(indent).AppendLine("/// </summary>");
        }

        private static int CompareConstants(OrderConstant left, OrderConstant right)
        {
            int byValue = left.Value.CompareTo(right.Value);
            return byValue != 0
                ? byValue
                : string.CompareOrdinal(left.Name, right.Name);
        }

        private static string Escape(string text) => text.Replace("&", "&amp;")
            .Replace("<", "&lt;")
            .Replace(">", "&gt;")
            .Replace("\r", string.Empty);

        private static string ToValidIdentifier(string raw)
        {
            if (string.IsNullOrWhiteSpace(raw))
                return string.Empty;

            StringBuilder builder = new(raw.Length);

            foreach (char symbol in raw)
            {
                if (char.IsLetterOrDigit(symbol))
                    builder.Append(symbol);
            }

            if (builder.Length == 0)
                return string.Empty;

            if (char.IsDigit(builder[0]))
                builder.Insert(0, '_');

            return builder.ToString();
        }
    }
}