#if UNITY_EDITOR
using System.IO;
using System.Linq;
using System.Text;
using Base.ToolPackage.MenuManagerWindow;
using UnityEditor;
using UnityEngine;

namespace Base.CorePackage.MenuManaging.Identifier.Editor
{
    /// <summary>
    /// Editor utility that scans the project for all <see cref="MenuIdentifier"/> assets and generates
    /// a static accessor class for them, as well as a registry asset for runtime resolution.
    /// </summary>
    public static class MenuIdentifierGenerator
    {
        private const string DefaultRegistryDirectory = "Assets/Generated/Resources";
        private const string LoaderNamespace = "Base.CorePackage.MenuManaging.Identifier";
        private const string MenuIdentifierNamespace = "Base.CorePackage.MenuManaging";
        private const string Namespace = "Base.CorePackage.MenuManaging.Generated";
        private const string OutputPath = "Assets/Generated/MenuIdentifiers/MenuIdentifiers.cs";
        private const string RegistryFileName = "MIR_Registry.asset";

        private static bool _pending;

        [DynamicMenuItem("Tools/Base Packages/Assets/Menu/Regenerate Menu Identifiers")]
        public static void Regenerate()
        {
            string[] guids = AssetDatabase.FindAssets($"t:{nameof(MenuIdentifier)}");
            var entries = guids
                .Select(g => new
                {
                    Guid = g,
                    Path = AssetDatabase.GUIDToAssetPath(g),
                    Asset = AssetDatabase.LoadAssetAtPath<MenuIdentifier>(AssetDatabase.GUIDToAssetPath(g))
                })
                .Where(e => e.Asset != null)
                .OrderBy(e => e.Asset.name)
                .ToArray();

            // Detect duplicate names, these would create invalid C#.
            var duplicates = entries
                .GroupBy(e => SanitizeIdentifier(e.Asset.name))
                .Where(g => g.Count() > 1)
                .ToArray();

            if (duplicates.Any())
            {
                foreach (var dup in duplicates)
                {
                    Debug.LogError($"Duplicate {nameof(MenuIdentifier)} name '{dup.Key}'. "
                        + $"Conflicts: {string.Join(", ", dup.Select(d => d.Path))}");
                }

                return;
            }

            // 1. Build / update the registry asset
            MenuIdentifierRegistry registry = ResolveRegistry();

            // Only write when the set actually changed, otherwise the asset gets rewritten
            // on every run and shows up as modified in version control for no reason.
            MenuIdentifier[] assetArray = entries.Select(e => e.Asset).ToArray();
            if (!registry.EntriesEqual(assetArray))
            {
                registry.SetEntries(assetArray);
                EditorUtility.SetDirty(registry);
            }

            // 2. Generate the static accessor class
            StringBuilder sb = new();
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("// This file is auto-generated. Do not edit manually.");
            sb.AppendLine("// Regenerate via Tools > Menus > Regenerate Menu Identifiers.");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine();
            sb.AppendLine($"using {MenuIdentifierNamespace};");
            sb.AppendLine($"using {LoaderNamespace};");
            sb.AppendLine();
            sb.AppendLine($"namespace {Namespace}");
            sb.AppendLine("{");
            sb.AppendLine("    /// <summary>");
            sb.AppendLine(
                "    /// Provides strongly-typed access to all <see cref=\"MenuIdentifier\"/> assets in the project.");

            sb.AppendLine(
                "    /// References are resolved lazily on first access via the <see cref=\"MenuIdentifierLoader\"/>.");

            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    public static class MenuIdentifiers");
            sb.AppendLine("    {");

            foreach (var entry in entries)
            {
                string identifier = SanitizeIdentifier(entry.Asset.name);
                sb.AppendLine($"        private static MenuIdentifier _{ToCamelCase(identifier)}; // reset-ignore");
                sb.AppendLine(
                    $"        public static MenuIdentifier {identifier} => _{ToCamelCase(identifier)} != null");

                sb.AppendLine($"            ? _{ToCamelCase(identifier)}");
                sb.AppendLine(
                    $"            : _{ToCamelCase(identifier)} = MenuIdentifierLoader.Load(\"{entry.Asset.name}\");");

                sb.AppendLine();
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");

            string newContents = sb.ToString();
            Directory.CreateDirectory(Path.GetDirectoryName(OutputPath)!);

            // Skip writing if nothing changed, avoids triggering pointless recompiles.
            if (File.Exists(OutputPath) && File.ReadAllText(OutputPath) == newContents)
            {
                AssetDatabase.SaveAssets();
                return;
            }

            File.WriteAllText(OutputPath, newContents);
            AssetDatabase.SaveAssets();
            AssetDatabase.Refresh();
            Debug.Log($"Generated MenuIdentifiers.cs with {entries.Length} entries.");
        }

        /// <summary>
        /// Queues a regeneration for the next editor tick.
        /// Asset callbacks must not create or refresh assets while an import is in flight,
        /// and a pending delete is only finished after the callback returns. Deferring also
        /// coalesces a batch of changes into a single run.
        /// </summary>
        internal static void ScheduleRegenerate()
        {
            if (_pending)
                return;

            _pending = true;
            EditorApplication.delayCall += RunPending;
        }

        private static void RunPending()
        {
            _pending = false;
            Regenerate();
        }

        /// <summary>
        /// Returns the single registry of the project. Finds it by type, so it can live in any
        /// directory the user picks. Creates one if none exists and deletes any duplicates.
        /// </summary>
        private static MenuIdentifierRegistry ResolveRegistry()
        {
            string[] paths = AssetDatabase.FindAssets($"t:{nameof(MenuIdentifierRegistry)}")
                .Select(AssetDatabase.GUIDToAssetPath)
                .Where(p => !string.IsNullOrEmpty(p))
                .OrderBy(p => p)
                .ToArray();

            if (paths.Length == 0)
                return CreateRegistry();

            // Only one registry may exist. Keep the first by path for a stable, deterministic
            // choice, and drop the rest so no stale copy can be picked up at runtime.
            string keptPath = paths[0];
            for (int i = 1; i < paths.Length; i++)
            {
                Debug.LogWarning($"Deleting duplicate MenuIdentifierRegistry at '{paths[i]}'. "
                    + $"Keeping '{keptPath}'.");

                AssetDatabase.DeleteAsset(paths[i]);
            }

            WarnIfOutsideResources(keptPath);
            return AssetDatabase.LoadAssetAtPath<MenuIdentifierRegistry>(keptPath);
        }

        private static MenuIdentifierRegistry CreateRegistry()
        {
            string path = $"{DefaultRegistryDirectory}/{RegistryFileName}";
            Directory.CreateDirectory(DefaultRegistryDirectory);
            AssetDatabase.Refresh();

            MenuIdentifierRegistry registry = ScriptableObject.CreateInstance<MenuIdentifierRegistry>();
            AssetDatabase.CreateAsset(registry, path);
            Debug.Log($"Created MenuIdentifierRegistry at '{path}'. Move it anywhere under a Resources folder.");

            return registry;
        }

        /// <summary>
        /// The registry is loaded through <see cref="UnityEngine.Resources"/> at runtime, so it is
        /// only included in a build when it sits under a Resources folder.
        /// </summary>
        private static void WarnIfOutsideResources(string path)
        {
            if (path.Contains("/Resources/"))
                return;

            Debug.LogWarning($"MenuIdentifierRegistry at '{path}' is not under a Resources folder "
                + "and will not be found in a build. Move it into one.");
        }

        private static string SanitizeIdentifier(string name)
        {
            StringBuilder sb = new();
            foreach (char c in name)
            {
                if (char.IsLetterOrDigit(c) || c == '_')
                    sb.Append(c);
            }

            string result = sb.ToString();
            if (result.Length == 0 || char.IsDigit(result[0]))
                result = "_" + result;

            return result;
        }

        private static string ToCamelCase(string s) => s.Length == 0
            ? s
            : char.ToLowerInvariant(s[0]) + s[1..];
    }
}
#endif