using System;
using System.Collections.Generic;
using System.Text.RegularExpressions;
using Base.ToolsPackage.Editor.Shared;
using Base.UtilityPackage.Logging;
using UnityEngine;

namespace Base.ToolsPackage.Editor.NamespaceConventionValidator
{
    /// <summary>
    /// Walks the scripts below the configured root and reports every namespace that does not read as
    /// the folder it sits in.
    /// <para>
    /// A namespace and the folder around it drift apart in exactly one way, and it is invisible: a file
    /// that is moved keeps the namespace of where it used to live, and the compiler is perfectly happy
    /// about that. Nothing else notices, so the two only ever come back together by hand.
    /// </para>
    /// <para>
    /// Where an assembly definition owns the folder, its root namespace is the point the path is
    /// measured from. Where none does, which is the normal case in a game's own scripts, the configured
    /// root folder and root namespace take that job.
    /// </para>
    /// </summary>
    internal static class NamespaceConventionScanner
    {
        private const string AsmdefExtension = ".asmdef";
        private const string AsmdefFilter = "t:AssemblyDefinitionAsset";

        /// <summary>
        /// How far into a file the generated marker still counts as a header. A generator that writes
        /// the marker into the file it produces carries the same text far below this, and is not itself
        /// generated.
        /// </summary>
        private const int GeneratedHeaderLength = 400;

        private const string GeneratedMarker = "<auto-generated>";
        private const string MissingIndexMessage = "Scanning needs an asset index to read the project through.";
        private const char NamespaceSeparator = '.';
        private const char PathSeparator = '/';
        private const string ScriptExtension = ".cs";
        private const string ScriptFilter = "t:MonoScript";

        private static readonly Regex NamespacePattern =
            new(@"^\s*namespace\s+([\w.]+)", RegexOptions.Multiline | RegexOptions.Compiled);

        /// <summary>Scans the project and returns every violation, sorted by path.</summary>
        /// <param name="config">The rules to check against.</param>
        /// <param name="index">
        /// The project to read. Pass <see cref="AssetDatabaseIndex.Default"/> for the live one.
        /// </param>
        /// <returns>Every violation that was found, sorted by path.</returns>
        internal static List<NamespaceViolation> Scan(NamespaceConventionConfig config, IAssetIndex index)
        {
            List<NamespaceViolation> violations = new();

            if (config == null)
            {
                CustomLogger.LogError($"Scanning needs a {nameof(NamespaceConventionConfig)}.", null);
                return violations;
            }

            if (index == null)
            {
                CustomLogger.LogError(MissingIndexMessage, config);
                return violations;
            }

            string root = Normalize(config.RootFolder);

            if (!index.IsValidFolder(root))
            {
                CustomLogger.LogWarning($"The root folder \"{root}\" does not exist.", config);
                return violations;
            }

            List<string> assemblyFolders = new();
            Dictionary<string, string> rootNamespaceByFolder = new(StringComparer.Ordinal);

            CollectAssemblies(index, root, assemblyFolders, rootNamespaceByFolder);
            CollectViolations(config, index, root, assemblyFolders, rootNamespaceByFolder, violations);

            violations.Sort(Compare);
            return violations;
        }

        /// <summary>
        /// Builds the namespace a folder reads as, so the window can show what it expected next to what
        /// it found.
        /// </summary>
        /// <param name="folder">The folder the script sits in.</param>
        /// <param name="root">The normalized root folder of the scan.</param>
        /// <param name="rootNamespace">The prefix for folders no assembly definition owns.</param>
        /// <param name="assemblyFolders">The assembly folders, longest path first.</param>
        /// <param name="rootNamespaceByFolder">The root namespace of each assembly folder.</param>
        /// <returns>The expected namespace, or an empty string when nothing can be measured from.</returns>
        private static string Expected(string folder, string root, string rootNamespace,
            IReadOnlyList<string> assemblyFolders, IReadOnlyDictionary<string, string> rootNamespaceByFolder)
        {
            foreach (string assemblyFolder in assemblyFolders)
            {
                if (!IsInside(folder, assemblyFolder))
                    continue;

                return Combine(rootNamespaceByFolder[assemblyFolder], Relative(folder, assemblyFolder));
            }

            return IsInside(folder, root)
                ? Combine(rootNamespace, Relative(folder, root))
                : string.Empty;
        }

        private static string Normalize(string path) => string.IsNullOrWhiteSpace(path)
            ? string.Empty
            : path.Trim().Trim(PathSeparator);

        private static bool IsInside(string path, string folder)
            => string.Equals(path, folder, StringComparison.Ordinal)
                || path.StartsWith(folder + PathSeparator, StringComparison.Ordinal);

        private static string Relative(string path, string folder)
            => path[folder.Length..].Trim(PathSeparator).Replace(PathSeparator, NamespaceSeparator);

        private static string Combine(string prefix, string relative)
        {
            if (string.IsNullOrEmpty(prefix))
                return relative;

            return string.IsNullOrEmpty(relative)
                ? prefix
                : prefix + NamespaceSeparator + relative;
        }

        private static string FolderOf(string path)
        {
            int end = path.LastIndexOf(PathSeparator);

            return end < 0
                ? string.Empty
                : path[..end];
        }

        private static string FileNameOf(string path) => path[(path.LastIndexOf(PathSeparator) + 1)..];

        /// <summary>
        /// Reads the declared namespace out of the source. The block form and the file scoped form start
        /// the same way, so one pattern reads either.
        /// </summary>
        private static string DeclaredNamespace(string source)
        {
            Match match = NamespacePattern.Match(source);

            return match.Success
                ? match.Groups[1].Value
                : string.Empty;
        }

        /// <summary>
        /// A generated file is rewritten on the next import. Only the header is read, because a tool
        /// that writes the marker into what it produces carries the same text far lower down.
        /// </summary>
        private static bool IsGenerated(string source)
        {
            int marker = source.IndexOf(GeneratedMarker, StringComparison.Ordinal);

            return marker >= 0
                && marker < GeneratedHeaderLength;
        }

        private static bool IsIgnored(string path, NamespaceConventionConfig config)
        {
            foreach (string ignored in config.IgnoredFileNames)
            {
                if (string.Equals(FileNameOf(path), ignored, StringComparison.Ordinal))
                    return true;
            }

            foreach (string ignored in config.IgnoredFolders)
            {
                if (path.Contains($"{PathSeparator}{ignored}{PathSeparator}", StringComparison.Ordinal))
                    return true;
            }

            return false;
        }

        private static int Compare(NamespaceViolation first, NamespaceViolation second)
            => string.Compare(first.Path, second.Path, StringComparison.Ordinal);

        private static void CollectAssemblies(IAssetIndex index, string root, List<string> assemblyFolders,
            IDictionary<string, string> rootNamespaceByFolder)
        {
            foreach (string path in index.FindAssetPaths(AsmdefFilter, root))
            {
                if (!path.EndsWith(AsmdefExtension, StringComparison.Ordinal))
                    continue;

                AsmdefManifest manifest = JsonUtility.FromJson<AsmdefManifest>(index.ReadText(path));

                if (manifest == null || string.IsNullOrEmpty(manifest.Name))
                    continue;

                string folder = FolderOf(path);

                assemblyFolders.Add(folder);
                rootNamespaceByFolder[folder] = string.IsNullOrEmpty(manifest.RootNamespace)
                    ? manifest.Name
                    : manifest.RootNamespace;
            }

            // Longest first, so a file inside a nested assembly is attributed to that one rather than to
            // the assembly whose folder merely contains it.
            assemblyFolders.Sort(comparison: static (first, second) => second.Length.CompareTo(first.Length));
        }

        private static void CollectViolations(NamespaceConventionConfig config, IAssetIndex index, string root,
            IReadOnlyList<string> assemblyFolders, IReadOnlyDictionary<string, string> rootNamespaceByFolder,
            ICollection<NamespaceViolation> violations)
        {
            foreach (string path in index.FindAssetPaths(ScriptFilter, root))
            {
                if (!path.EndsWith(ScriptExtension, StringComparison.Ordinal)
                    || IsIgnored(path, config))
                    continue;

                string source = index.ReadText(path);

                if (string.IsNullOrEmpty(source))
                    continue;

                if (config.IgnoreGeneratedFiles
                    && IsGenerated(source))
                    continue;

                Inspect(config, path, source, root, assemblyFolders, rootNamespaceByFolder, violations);
            }
        }

        private static void Inspect(NamespaceConventionConfig config, string path, string source, string root,
            IReadOnlyList<string> assemblyFolders, IReadOnlyDictionary<string, string> rootNamespaceByFolder,
            ICollection<NamespaceViolation> violations)
        {
            string declared = DeclaredNamespace(source);

            if (string.IsNullOrEmpty(declared))
            {
                if (config.RequireNamespace)
                    violations.Add(new NamespaceViolation(ENamespaceViolationType.MissingNamespace, path,
                        "Declares no namespace, so its types land in the global one."));

                return;
            }

            string expected = Expected(FolderOf(path), root, config.RootNamespace, assemblyFolders,
                rootNamespaceByFolder);

            // Nothing to measure against means nothing to report. That is a script outside the root, or
            // one in a root that names no namespace of its own.
            if (string.IsNullOrEmpty(expected)
                || string.Equals(declared, expected, StringComparison.Ordinal))
                return;

            if (config.AllowShorterNamespace
                && expected.StartsWith(declared + NamespaceSeparator, StringComparison.Ordinal))
                return;

            violations.Add(new NamespaceViolation(ENamespaceViolationType.MismatchedNamespace, path,
                $"Declares {declared} but sits in a folder that reads {expected}."));
        }
    }
}