#if UNITY_EDITOR
using System.IO;
using System.Linq;
using System.Text;
using UnityEditor;
using UnityEngine;

namespace Base.SystemsCorePackage.MenuManaging.Identifier.Editor
{
    /// <summary>
    /// Editor utility that scans the project for all <see cref="MenuIdentifier"/> assets and generates
    /// a static accessor class for them, as well as a registry asset for runtime resolution.
    /// </summary>
    public static class MenuIdentifierGenerator
    {
        private const string OutputPath = "Assets/Generated/MenuIdentifiers.cs";
        private const string RegistryPath = "Assets/Generated/Resources/MenuIdentifierRegistry.asset";
        private const string Namespace = "Base.SystemsCorePackage.MenuManaging.Generated";
        private const string MenuIdentifierNamespace = "Base.SystemsCorePackage.MenuManaging";
        private const string LoaderNamespace = "Base.SystemsCorePackage.MenuManaging.Identifier";

        [MenuItem("Tools/Base Packages/Menu/Regenerate Menu Identifiers", priority = 2)]
        public static void Regenerate()
        {
            string[] guids = AssetDatabase.FindAssets($"t:{nameof(MenuIdentifier)}");
            var entries = guids
                .Select(g => new
                {
                    Guid = g,
                    Path = AssetDatabase.GUIDToAssetPath(g),
                    Asset = AssetDatabase.LoadAssetAtPath<MenuIdentifier>(AssetDatabase.GUIDToAssetPath(g))
                })
                .Where(e => e.Asset != null)
                .OrderBy(e => e.Asset.name)
                .ToArray();

            // Detect duplicate names — these would create invalid C#.
            var duplicates = entries
                .GroupBy(e => SanitizeIdentifier(e.Asset.name))
                .Where(g => g.Count() > 1)
                .ToArray();

            if (duplicates.Any())
            {
                foreach (var dup in duplicates)
                    Debug.LogError($"Duplicate MenuIdentifier name '{dup.Key}'. " +
                                   $"Conflicts: {string.Join(", ", dup.Select(d => d.Path))}");
                return;
            }

            // 1. Build / update the registry asset
            MenuIdentifierRegistry registry = AssetDatabase.LoadAssetAtPath<MenuIdentifierRegistry>(RegistryPath);
            if (registry == null)
            {
                Directory.CreateDirectory(Path.GetDirectoryName(RegistryPath)!);
                registry = ScriptableObject.CreateInstance<MenuIdentifierRegistry>();
                AssetDatabase.CreateAsset(registry, RegistryPath);
            }

            registry.SetEntries(entries.Select(e => e.Asset).ToArray());
            EditorUtility.SetDirty(registry);

            // 2. Generate the static accessor class
            StringBuilder sb = new();
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("// This file is auto-generated. Do not edit manually.");
            sb.AppendLine("// Regenerate via Tools > Menus > Regenerate Menu Identifiers.");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine();
            sb.AppendLine($"using {MenuIdentifierNamespace};");
            sb.AppendLine($"using {LoaderNamespace};");
            sb.AppendLine();
            sb.AppendLine($"namespace {Namespace}");
            sb.AppendLine("{");
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// Provides strongly-typed access to all <see cref=\"MenuIdentifier\"/> assets in the project.");
            sb.AppendLine("    /// References are resolved lazily on first access via the <see cref=\"MenuIdentifierLoader\"/>.");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    public static class MenuIdentifiers");
            sb.AppendLine("    {");

            foreach (var entry in entries)
            {
                string identifier = SanitizeIdentifier(entry.Asset.name);
                sb.AppendLine($"        private static MenuIdentifier _{ToCamelCase(identifier)};");
                sb.AppendLine($"        public static MenuIdentifier {identifier} => _{ToCamelCase(identifier)} != null");
                sb.AppendLine($"            ? _{ToCamelCase(identifier)}");
                sb.AppendLine($"            : _{ToCamelCase(identifier)} = MenuIdentifierLoader.Load(\"{entry.Asset.name}\");");
                sb.AppendLine();
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");

            string newContents = sb.ToString();
            Directory.CreateDirectory(Path.GetDirectoryName(OutputPath)!);

            // Skip writing if nothing changed — avoids triggering pointless recompiles.
            if (File.Exists(OutputPath) && File.ReadAllText(OutputPath) == newContents)
            {
                AssetDatabase.SaveAssets();
                return;
            }

            File.WriteAllText(OutputPath, newContents);
            AssetDatabase.SaveAssets();
            AssetDatabase.Refresh();
            Debug.Log($"Generated MenuIdentifiers.cs with {entries.Length} entries.");
        }

        private static string SanitizeIdentifier(string name)
        {
            StringBuilder sb = new();
            foreach (char c in name)
                if (char.IsLetterOrDigit(c) || c == '_')
                    sb.Append(c);

            string result = sb.ToString();
            if (result.Length == 0 || char.IsDigit(result[0]))
                result = "_" + result;

            return result;
        }

        private static string ToCamelCase(string s) => s.Length == 0 ? s : char.ToLowerInvariant(s[0]) + s[1..];
    }
}
#endif