using UnityEngine;

namespace Base.ScreenShakePackage
{
    /// <summary>
    /// Base class for generating screen shake effects in response to gameplay events.
    /// </summary>
    [RequireComponent(typeof(CinemachineImpulseSourceWrapper))]
    public abstract class BaseScreenShakeGenerator : MonoBehaviour
    {
        [Tooltip("Multiplier for the screen shake intensity generated by this component.")]
        [SerializeField] protected float multiplier = 1f;

        protected CinemachineImpulseSourceWrapper ImpulseSourceWrapper { get; private set; }

#region Unity Callbacks
        private void Awake() => ImpulseSourceWrapper = GetComponent<CinemachineImpulseSourceWrapper>();
#endregion
    }
}