using Base.AttributePackage;
using UnityEngine;

namespace Base.ScreenShakePackage
{
    /// <summary>
    /// Base class for generating screen shake effects in response to gameplay events.
    /// </summary>
    [RequireComponent(typeof(CinemachineImpulseSourceWrapper))]
    public abstract class BaseScreenShakeGenerator : MonoBehaviour
    {
        [Tooltip("Multiplier for the screen shake intensity generated by this component.")]
        [SerializeField] protected float multiplier = 1f;

        [GetComponent] [Required]
        [SerializeField] protected CinemachineImpulseSourceWrapper impulseSourceWrapper;
    }
}