// <auto-generated>
// Generated by the Order Manager. Do not edit by hand.
// </auto-generated>

namespace Base.ToolPackage.Editor.Generated
{
    public static class MenuOrders
    {
        /// <summary>Shared tools every team member uses, such as localization tables or the asset zoo generator.</summary>
        public const int Team = -47;

        /// <summary>Windows for asset actions like finding missing references or generating asset IDs.</summary>
        public const int Asset = -36;

        /// <summary>Code health and inspection tools.</summary>
        public const int Code = -25;

        /// <summary>Profiling utilities like the memory profiler.</summary>
        public const int Profiling = -11;
    }
}
